# Generated by Django 4.2.7 on 2024-01-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='is_acrive',
            new_name='is_active',
        ),
    ]
