# Generated by Django 4.2.7 on 2024-02-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_slug_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Номер версии')),
                ('version_name', models.CharField(max_length=255, verbose_name='название версии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Текущая версия')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
